# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
