# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0004_auto_20190926_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='dash_app.User'),
        ),
    ]
