# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-03 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0008_remove_quotes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='liked_by',
            field=models.ManyToManyField(related_name='quotes_liked', to='dash_app.User'),
        ),
    ]
